extends Node

# GOTOT-013 - Meshlets / LOD / Cluster Culling (SPEC 013)
#
# Uses the GOTOT-001B GPU scene (transform buffer) + the offline-built
# mesh_013_torus.gomlet (meshoptimizer 1.2, generated by
# tools/meshlet_import - the runtime is meshoptimizer-FREE). The runtime API
# (modules/gotot_render) is additive: nothing here touches 001A..011.
#
# Fixed scene (camera (0,0,2000), identity, FOV 60, near=300 far=4000; lod
# thresholds t0=2200 / t1=3200) with 6 instances of the shared torus mesh
# (R=300, r=60, axis = Z, flat ring facing the camera):
#   inst 0: (0,0,0)       dist 2000   -> LOD0
#   inst 1: (0,0,-400)    dist 2400   -> LOD1
#   inst 2: (0,0,-800)    dist 2800   -> LOD1
#   inst 3: (0,0,-1400)   dist 3400   -> LOD2
#   inst 4: (3000,0,0)    dist 3605   -> LOD2, OFF-FRUSTUM (culled)
#   inst 5: (0,0,2500)    dist 500    -> LOD0, BEHIND camera (culled)
#
# Evidence targets (8 PASS criteria):
#   (1) >= 1M triangle meshlet scene (LOD0 = 1,048,576 tris);
#   (2) >= 10K meshlets (LOD0 = 10,905; total = 18,613);
#   (3) cluster_visible < cluster_total (frustum + cone backface culling);
#   (4) LOD changes with distance (instance_lods == [0,1,1,2,2,0]);
#   (5) DET signature stable (in-binary full double dispatch + harness rerun);
#   (6) software rasterizer makes sub-pixel triangles visible
#       (subpixel_px > 0 && covered_px > 0 && covered == winner px);
#   (7) rasterizers/cull counters agree (winner px == covered counter);
#   (8) regressions 001A..011 exit 0 (backwards compatibility, enforced by
#       the regression harness, not by this scene).

const INSTANCE_COUNT := 6
const RASTER_W := 1920
const RASTER_H := 1080
const MIN_LOD0_TRIS := 1000000
const MIN_TOTAL_MESHLETS := 10000
const CAM_POS := Vector3(0, 0, 2000)

var sig_file := "C:/Users/opc/AppData/Local/Temp/opencode/gt013_sig.txt"
var asset_path := "res://mesh_013_torus.gomlet"

var server: GototRenderServer
var camera: Camera3D

var sig := ""
var pass_count := 0

var inst_lods := PackedInt32Array()
var cc1 := PackedInt32Array()
var cc1_cull := PackedInt32Array()
var ev1 := PackedFloat32Array()
var stats := PackedInt32Array()

func _ready() -> void:
	_parse_user_args()
	server = GototRenderServer.get_server_singleton()
	if server == null:
		_fail(130, "server singleton is null")
		return
	if not server.ensure_gpu_device():
		_fail(131, "local RenderingDevice not available")
		return

	camera = $Camera
	camera.global_position = CAM_POS
	camera.rotation = Vector3.ZERO
	camera.near = 300.0
	camera.far = 4000.0

	if not server.gpu_scene_create(INSTANCE_COUNT, 1.0):
		_fail(132, "gpu_scene_create")
		return
	if not server.gpu_scene_dispatch(13):
		_fail(133, "gpu_scene_dispatch")
		return

	var positions := [
		Vector3(0, 0, 0), Vector3(0, 0, -400), Vector3(0, 0, -800),
		Vector3(0, 0, -1400), Vector3(3000, 0, 0), Vector3(0, 0, 2500),
	]
	for i in INSTANCE_COUNT:
		server.gpu_scene_set_instance_transform(i, positions[i], 1.0)

	server.gpu_scene_set_viewport(1920.0, 1080.0)
	server.gpu_scene_set_camera(camera.get_global_transform(), camera.get_camera_projection())

	var bytes := _read_asset(asset_path)
	print("GOTOT-NEXT 013: asset bytes=", bytes.size())
	if bytes.size() < 20:
		_fail(134, "asset read failed/empty: " + asset_path)
		return
	if not server.gpu_meshlet_load(bytes):
		_fail(135, "gpu_meshlet_load")
		return
	if not server.gpu_meshlet_set_lod_thresholds(2200.0, 3200.0):
		_fail(136, "gpu_meshlet_set_lod_thresholds")
		return

	stats = server.gpu_meshlet_stats()
	# Criterion (1): >= 1M triangle meshlet scene.
	if stats.size() < 5:
		_fail(137, "stats size")
		return
	if server.gpu_meshlet_get_lod0_tri_count() < MIN_LOD0_TRIS:
		_fail(138, "lod0_tri_count " + str(server.gpu_meshlet_get_lod0_tri_count()) + " < " + str(MIN_LOD0_TRIS))
		return
	if server.gpu_meshlet_get_total_meshlets() < MIN_TOTAL_MESHLETS:
		_fail(139, "total_meshlets too small")
		return
	# Criterion (2): >= 10K meshlets (LOD0 count).
	if server.gpu_meshlet_get_lod0_meshlet_count() < 10000:
		_fail(140, "lod0_meshlet_count < 10000")
		return

	if not _full_pipeline():
		return

	if not _det_check():
		return

	var covered := int(ev1[0])
	var subpixel := int(ev1[1])
	var winner := int(ev1[2])
	var fnv := int(ev1[3])
	sig = "sig=v13|t%d|m%d|l0m%d|l%s|a%d/%d/%d|cc%d/%d|pn%d/%d/%d|cov%d|sp%d|w%d|f%d|d%d" % [
		stats[1], stats[0], stats[2], _lods_str(),
		cc1[4], cc1[5], cc1[6], cc1[0], cc1[1],
		cc1[5], cc1[6], cc1[7], covered, subpixel, winner, fnv, 1 if pass_count >= 6 else 0]
	print("GOTOT-NEXT 013: ", sig)
	var f := FileAccess.open(sig_file, FileAccess.WRITE)
	if f == null:
		print("GOTOT-NEXT 013: sig file WRITE FAILED: ", sig_file)
	else:
		f.store_line(sig)
		f.close()

	print("GOTOT-NEXT 013: PASS")
	server.gpu_meshlet_destroy()
	server.gpu_scene_destroy()
	get_tree().quit(0)

func _parse_user_args() -> void:
	for a in OS.get_cmdline_user_args():
		var kv := a.split("=")
		if kv.size() != 2:
			continue
		if kv[0] == "--sigf":
			sig_file = kv[1]
		elif kv[0] == "--asset":
			asset_path = kv[1]

func _read_asset(path: String) -> PackedByteArray:
	var f := FileAccess.open(path, FileAccess.READ)
	if f == null or not f.is_open():
		return PackedByteArray()
	var n: int = f.get_length()
	if n <= 0:
		return PackedByteArray()
	var v := f.get_buffer(n)
	f.close()
	var out := PackedByteArray()
	out.resize(n)
	for i in n:
		out[i] = v[i]
	return out

func _full_pipeline() -> bool:
	# Cull + raster once, snapshot all deterministic evidence.
	if not server.gpu_meshlet_cull_dispatch():
		_fail(141, "gpu_meshlet_cull_dispatch")
		return false
	inst_lods = server.gpu_meshlet_get_instance_lods()
	cc1 = server.gpu_meshlet_get_cluster_counts()
	cc1_cull = cc1
	var dbg := server.gpu_meshlet_get_cull_debug()
	print("GOTOT-NEXT 013: dbg=", dbg)
	if dbg.size() >= 8:
		print("GOTOT-NEXT 013: dbg lod_mc=", [dbg[0], dbg[1], dbg[2]],
			" expect=[10905,5507,2201] marker=", dbg[3],
			" lod0_ord=", dbg[4], " ml0=", dbg[5], " hdr=", dbg[6], " pad=", dbg[7])
	if dbg.size() >= 16:
		print("--- Test B2: raw desc[0..1] ---")
		print("desc[0] = (", dbg[8], ",", dbg[9], ",", dbg[10], ",", dbg[11], ")",
			"  LOD0 a=(vert_base,tri_base,ordinal,pad) expect=(0,0,3,0)")
		print("desc[1] = (", dbg[12], ",", dbg[13], ",", dbg[14], ",", dbg[15], ")",
			"  LOD0 b=(vc,tc,mc,pad) expect=(524288,1048576,10905,0)")
	if inst_lods.size() != INSTANCE_COUNT:
		_fail(142, "instance_lods size")
		return false
	# Criterion (4): LOD changes with distance -> [0,1,1,2,2,0].
	var expect := PackedInt32Array([0, 1, 1, 2, 2, 0])
	if inst_lods != expect:
		_fail(143, "instance_lods " + _lods_str() + " != expected 0,1,1,2,2,0")
		return false

	# Criterion (3): cluster_visible < cluster_total.
	var total := cc1[0]
	var visible := cc1[1]
	if total <= 0:
		_fail(144, "total clusters == 0")
		return false
	if not (visible < total):
		_fail(145, "cluster_visible " + str(visible) + " not < cluster_total " + str(total))
		return false
	if visible <= 0:
		_fail(146, "cluster_visible == 0")
		return false

	if not server.gpu_meshlet_raster_dispatch():
		_fail(147, "gpu_meshlet_raster_dispatch")
		return false
	ev1 = server.gpu_meshlet_raster_evidence()
	if ev1.size() < 4:
		_fail(148, "raster_evidence size")
		return false
	cc1 = server.gpu_meshlet_get_cluster_counts()
	var dbg2 := server.gpu_meshlet_get_cull_debug()
	if dbg2.size() >= 24:
		print("=== Test B3: Raster diagnostics ===")
		print("triangles_processed=", dbg2[16])
		print("triangles_projected_ok=", dbg2[17])
		print("pass0_winners=", dbg2[18])
		print("pass1_hits=", dbg2[19])
		print("LOD2_diag (cx,cy) [24..29]=", [dbg2[24], dbg2[25], dbg2[26], dbg2[27], dbg2[28], dbg2[29]])
	print("covered_px=", int(ev1[0]), " subpixel_px=", int(ev1[1]), " winner_px=", int(ev1[2]))
	var covered := int(ev1[0])
	var subpixel := int(ev1[1])
	var winner := int(ev1[2])
	# Criterion (6)+(7): software rasterization happened, sub-pixel triangles
	# were made visible, and the covered/winner counts agree.
	if covered <= 0:
		_fail(149, "covered_px == 0")
		return false
	if subpixel <= 0:
		_fail(150, "subpixel_px == 0 (no sub-pixel triangles made visible)")
		return false
	if covered != winner:
		_fail(151, "covered " + str(covered) + " != winner px " + str(winner))
		return false
	# Every LOD used by a visible instance contributes pixels (px_lod slots 7..9).
	if cc1[7] <= 0 or cc1[8] <= 0 or cc1[9] <= 0:
		_fail(152, "per-LOD pixel cover empty: " + str([cc1[7], cc1[8], cc1[9]]))
		return false
	# Instance lods actually used show up in the visible-per-LOD cluster counts (slots 4..6).
	if cc1[4] <= 0 or cc1[5] <= 0 or cc1[6] <= 0:
		_fail(153, "per-LOD cluster visibility empty")
		return false
	pass_count += 5
	return true

func _det_check() -> bool:
	# In-binary determinism: rerun the FULL cull+raster pipeline and compare
	# every readback exactly (criterion 5).
	if not server.gpu_meshlet_cull_dispatch():
		_fail(154, "DET cull")
		return false
	var lods2 := server.gpu_meshlet_get_instance_lods()
	var cc2 := server.gpu_meshlet_get_cluster_counts()
	if lods2 != inst_lods:
		_fail(155, "DET instance_lods differ")
		return false
	if cc2 != cc1_cull:
		_fail(156, "DET cluster counts differ")
		return false
	if not server.gpu_meshlet_raster_dispatch():
		_fail(157, "DET raster")
		return false
	var ev2 := server.gpu_meshlet_raster_evidence()
	if ev2 != ev1:
		_fail(158, "DET raster evidence differs")
		return false
	pass_count += 1
	return true

func _lods_str() -> String:
	var parts := PackedStringArray()
	for l in inst_lods:
		parts.append(str(l))
	return ",".join(parts)

func _fail(code: int, msg: String) -> void:
	print("GOTOT-NEXT 013: FAIL code=", code, " ", msg)
	if server != null:
		server.gpu_meshlet_destroy()
		server.gpu_scene_destroy()
	get_tree().quit(code)