#!/usr/bin/env python

from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_modules.Append(CPPDEFINES=["GOTOT_RENDER_ENABLED"])

sources = [
    "register_types.cpp",
    "gotot_render.cpp",
    "gotot_render_server.cpp",
]

env_gotot_render = env_modules.Clone()
env_gotot_render.add_source_files(env.modules_sources, sources)